name: Publish Docker Image

# !!! NEVER add on push when there is on workflow_call
# if you do that the workflow can run multiple times
# for instance if you re-use this docker build workflow for prod deployment and for local-env in PR
# it will build the docker image it twice
# if you build => deploy => run e2e against prod it will build the image 3 times!
on:
  workflow_call:
    inputs:
      # Build-args used to define variables that will be used in image
      # Example of build-args: "|
                          #EXCLUDE_UNIT_TESTS_FROM_BUILD=true"
      build-args:
        required: false
        type: string
      # Prefix used to be able to build images for local-env and prod-env with different tags
      # prefix is also used to write current env to digest name to be able to build several docker images for several envs in one workflow
      # Example of prefix: local-env
      prefix:
        required: false
        type: string

jobs:
  build-amd64:
    uses: ./.github/workflows/.reusable-docker-digest-build-and-push.yml
    with:
      platform: amd64
      build-args: ${{ inputs.build-args }}
      prefix: ${{ inputs.prefix }}
    # without this it cannot login to the registry
    secrets: inherit

  build-arm64:
    uses: ./.github/workflows/.reusable-docker-digest-build-and-push.yml
    with:
      platform: arm64
      build-args: ${{ inputs.build-args }}
      prefix: ${{ inputs.prefix }}  
    # without this it cannot login to the registry
    secrets: inherit

  merge:
    runs-on: ubuntu-22.04
    needs:
      - build-amd64
      - build-arm64
    steps:
      # this is needed to address this issue according to the comment https://github.com/devcontainers/ci/issues/271#issuecomment-2301764487
      # otherwise our TourmalineCore org name cannot be used in docker image names, only tourmalinecore
      - name: Add Registry Image Env Var With Lowercase Organization and Repo Name
        run: |
          echo "REGISTRY_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          # Prefix is needed to explicitly split digests by it's environment and download digests only for current environment
          # and avoid using local env image in prod
          # Example of digest name: local-env-digests-linux-amd64
          pattern: ${{ inputs.prefix && format('{0}-', inputs.prefix) || '' }}digests-*
          merge-multiple: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ inputs.prefix && format('{0}-', inputs.prefix) || '' }}latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha,prefix=${{ inputs.prefix && format('{0}-', inputs.prefix) || '' }}sha-
            type=sha,format=long,prefix=${{ inputs.prefix && format('{0}-', inputs.prefix) || '' }}sha-
        env:
          # https://github.com/docker/metadata-action/issues/283
          # without this flag it won't tag the image using the commit SHA 
          # for non push events like pull_request ones it requires this :(
          DOCKER_METADATA_PR_HEAD_SHA: true

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}