name: Publish Docker Image by Digest

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      # Build-args used to define variables that will be used in image
      # Example of build-args: "|
                          #EXCLUDE_UNIT_TESTS_FROM_BUILD=true"
      build-args:
        required: false
        type: string
      # Prefix used to be able to build images for local-env and prod-env with different tags
      # prefix is also used to write current env to digest name to be able to build several docker images for several envs in one workflow
      # Example of prefix: local-env
      prefix:
        required: false
        type: string
  
jobs:
  build-digest:
    # Examples of runs-on platform: ubuntu-24.04, ubuntu-24.04-arm
    runs-on: ${{ inputs.platform == 'amd64' && 'ubuntu-24.04' || inputs.platform == 'arm64' && 'ubuntu-24.04-arm'}}
    steps:
      # this is needed to address this issue according to the comment https://github.com/devcontainers/ci/issues/271#issuecomment-2301764487
      # otherwise our TourmalineCore org name cannot be used in docker image names, only tourmalinecore
      - name: Add Registry Image Env Var With Lowercase Organization and Repo Name
        run: |
          echo "REGISTRY_IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Prepare
        run: |
          # Examples of digest_platform: linux/amd64, linux/arm64
          digest_platform=linux/${{ inputs.platform }}
          echo "digest-platform=$digest_platform" >> $GITHUB_ENV

      - name: Prepare
        run: |
          # Examples of digest_platform: linux/amd64, linux/arm64
          digest_platform=linux/${{ inputs.platform }}
          echo "digest-platform=$digest_platform" >> $GITHUB_ENV

          # Examples of digest_name: local-env-digests-linux-amd64, digests-linux-arm64
          digest_name=${{ inputs.prefix && format('{0}-', inputs.prefix) || '' }}digests-${digest_platform//\//-}
          echo "digest-name=$digest_name" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.digest-platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          build-args: ${{ inputs.build-args }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.digest-name }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1