name: Publish Docker Image by Digest

on:
  workflow_call:
    inputs:
      runner-platform:
        required: true
        type: string
      target-arch:
        required: true
        type: string
      # Prefix used to be able to build images for local-env and prod-env with different tags
      # Example of prefix: local-env
      prefix:
        required: false
        type: string
      # Build-args used to define variables that will be used in image
      # Example of build-args: "|
                          #CDN_ENABLED=true
                          #CDN_DOMAIN=cdn.domain.com"
      build-args:
        required: false
        type: string
      # build-env is used to write current env to digest name to be able to build several docker images for several envs in one workflow
      # Example of build-env: local
      build-env:
        required: false
        type: string

jobs:
  build_digest:
    runs-on: {{ inputs.runner-platform }}
    steps:
      - name: Prepare
        run: |
          echo "PLATFORM_PAIR=${inputs.target-arch//\//-}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tourmalinecore/${{ github.event.repository.name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.PLATFORM_PAIR }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/tourmalinecore/${{ github.event.repository.name }}
          build-args: ${{ inputs.build-args }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          # Prefix build-env is needed to explicitly split digests by it's environment and download digests only for current environment
          # and avoid using local env image in prod
          # Example of digest name: local-digests-linux-amd64
          name: ${{ inputs.build-env && format('{0}-', inputs.build-env) || '' }}digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1